<?php

namespace Tests\Feature;

use App\Models\UserEmployer;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserEmployerTest extends TestCase
{
    use RefreshDatabase;

    private string $token;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = UserEmployer::factory()->create();
        $this->token = $user->createToken('auth-token', ['role:employer'])->plainTextToken;
    }

    public function test_get_user_employer()
    {
        $response = $this->get('/api/v1/employer/me', ['Authorization' => 'Bearer ' . $this->token]);
        $response->assertStatus(200);
        $response->assertJsonStructure([
            "data" => [
                "name",
                "surname",
            ]
        ]);
    }
}
