<?php

namespace Tests\Feature;

use App\Models\UserEmployer;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Hash;
use Tests\TestCase;

class UserEmployerTest extends TestCase
{
    use RefreshDatabase;

    private string $token;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $user = UserEmployer::factory(['password' => Hash::make('testtest')])->create();
        $this->token = $user->createToken('auth-token', ['role:employer'])->plainTextToken;
    }

    public function test_get_user_employer()
    {
        $response = $this->get('/api/v1/employer/me', ['Authorization' => 'Bearer ' . $this->token]);
        $response->assertStatus(200);
        $response->assertJsonStructure([
            "data" => [
                "name",
                "surname",
            ]
        ]);
    }

    public function test_update_user_employer()
    {
        $response = $this->put('/api/v1/employer/', [
            'name' => 'Тест',
            'surname' => 'Тестов',
            'lastname' => 'Тестович',
            'password' => 'testtest',
            'new_password' => 'testtest2'
        ], ['Authorization' => 'Bearer ' . $this->token]);
        $response->assertStatus(200);
        $response->assertJsonStructure([
            "data" => [
                "name",
                "surname",
            ]
        ]);
    }
}
