on:
  push:
    branches:
      - main
jobs:
  tests:
    env:
      DB_PASSWORD: postgres
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: rabotaclick
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.21.2
        with:
          php-version: 8.2
      - run: cp .env.example .env
      - run: composer install -n --prefer-dist
      - run: php artisan key:generate
      - run: php artisan test
